- SortingAlgorithms.cpp
A file containing implementation of all major sorting algorithms.
> Sorting Algorithms

- Binary Matrix.cpp
Adding a new program binary matrix to the repository
> Binary Matrix

- cityTravel.java
> city travel

- binarySearch.java
A simple binary search algorithm in java
> Binary Search

- radix-sort.cpp
Hi i have added the implementation of radix sort to ur repo.Also doing a PR for hactoberfest.Thanks.
> Radix Sort

- captcha.html
it is simple captcha in html which you can use any where on page
> Created captcha.html

- mergearray.java
> Potdukhe update

- Strings.java
> hactober tag

- quickSort.java
- radixSort.java
A simple quick sort algorithm and radix sort algorithm in Java
> Quick Sort and Radix Sort

- Traveling Salesman Problem (TSP) Implementation.py
Traveling Salesman Problem (TSP) Implementation
> Create Traveling Salesman Problem (TSP) Implementation.py

- DFT.c
> shreyas talwekar

- index.html
This is a Ecommerce Website Front Page
e
> Uploading Ecommerce Website Page

- Pallindromenumber.cpp
- Sort_Stack_Using_Recursion.cpp
- SquareRootOfInteger.cpp
- String_powerset.cpp
- primenumber.cpp
> I add CPP files

- implementation of 2D array in java
simplest way to implement array in java
> Simple 2D array implementation in java

- PHP/PHP_Contol_Statment.php
- PHP/PHP_Datatypes.php
- PHP/PHP_Operators.php
Added Php Language folder which has **Control Statment**, **Datatypes** and Different **Operators**.
> PHP Language Control Statment, Datatypes And Operators

- insertion sort in python.py
Insertion sort code in python with comments.
> Insertion sort

- Replace pi
Its a recursive program that replaces pi with 3.14 in a gives string
Example:- Input: ppxpixxpi
Output:ppx3.14xx3.14
> Create Replace pi

- Union of two arrays.cpp
Union of two arrays in C++ by aakash345 for hacktoberfest21
> Union of 2 arrays in C++

- Stock Buy and Sell.cpp
Please label it hactoberfest21 and merge it.
Thanks in advance.
> Added Stock Buy and Sell.cpp

- CountingSort.cpp
Counting Sort Algorithm with output example and comments for better understanding
> Counting Sort Algo
